-- AlterTable
ALTER TABLE "ItensPedido" ADD COLUMN     "QTD" INTEGER,
ADD COLUMN     "TAMANHO" TEXT;

-- AlterTable
ALTER TABLE "PEDIDOS" ADD COLUMN     "CODEND" INTEGER,
ADD COLUMN     "CODPES" INTEGER,
ALTER COLUMN "SUBTOTAL" DROP NOT NULL,
ALTER COLUMN "SUBTOTAL" SET DEFAULT 0,
ALTER COLUMN "VALORTOTAL" DROP NOT NULL,
ALTER COLUMN "VALORTOTAL" SET DEFAULT 0,
ALTER COLUMN "DESCONTO" DROP NOT NULL,
ALTER COLUMN "DESCONTO" SET DEFAULT 0,
ALTER COLUMN "FRETE" DROP NOT NULL,
ALTER COLUMN "FRETE" SET DEFAULT 0;

-- AlterTable
ALTER TABLE "PRODUTO" ALTER COLUMN "ESTOQUE" SET DEFAULT 0,
ALTER COLUMN "VALOR" SET DEFAULT 0,
ALTER COLUMN "DESCONTO" DROP NOT NULL,
ALTER COLUMN "DESCONTO" SET DEFAULT 0;

-- AddForeignKey
ALTER TABLE "PEDIDOS" ADD CONSTRAINT "PEDIDOS_CODEND_fkey" FOREIGN KEY ("CODEND") REFERENCES "ENDERECOS"("CODEND") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PEDIDOS" ADD CONSTRAINT "PEDIDOS_CODPES_fkey" FOREIGN KEY ("CODPES") REFERENCES "INFOS"("CODPES") ON DELETE SET NULL ON UPDATE CASCADE;
