version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "9080:5432"
    networks:
      - backend_network

  backend:
    image: pnunes276/zabbixstore-backend:latest
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - backend_network
    depends_on:
      - postgres  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000
    networks:
      - backend_network
    depends_on:
      - backend  

networks:
  backend_network:
    driver: bridge

volumes:
  postgres:
