FROM node:16-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE 3000
ENV DATABASE_URL="postgresql://postgres:postgres@172.17.0.1:5432"
RUN npx prisma generate
CMD ["npm", "run", "start:dev"]
