FROM node:16-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE 3000
ENV DATABASE_URL="postgresql://postgres:postgres@localhost:9080"
RUN npm prisma generate
CMD ["npm", "run", "start:dev"]
