-- CreateTable
CREATE TABLE "LOGIN" (
    "CODUSU" SERIAL NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "SENHA" TEXT NOT NULL,
    "PERMISSAO" TEXT DEFAULT 'CLIENTE',

    CONSTRAINT "LOGIN_pkey" PRIMARY KEY ("CODUSU")
);

-- CreateTable
CREATE TABLE "Categorias" (
    "CODCAT" SERIAL NOT NULL,
    "CATEGORIA" TEXT NOT NULL,

    CONSTRAINT "Categorias_pkey" PRIMARY KEY ("CODCAT")
);

-- CreateTable
CREATE TABLE "PRODUTO" (
    "CODPROD" SERIAL NOT NULL,
    "PRODUTO" TEXT NOT NULL,
    "DESCRICAO" TEXT NOT NULL,
    "IMAGEM" TEXT NOT NULL,
    "ESTOQUE" DOUBLE PRECISION NOT NULL,
    "VALOR" DOUBLE PRECISION NOT NULL,
    "DESCONTO" DOUBLE PRECISION NOT NULL,
    "CODCAT" INTEGER,

    CONSTRAINT "PRODUTO_pkey" PRIMARY KEY ("CODPROD")
);

-- CreateTable
CREATE TABLE "PEDIDOS" (
    "CODPED" SERIAL NOT NULL,
    "SUBTOTAL" DOUBLE PRECISION NOT NULL,
    "VALORTOTAL" DOUBLE PRECISION NOT NULL,
    "DESCONTO" DOUBLE PRECISION NOT NULL,
    "FRETE" DOUBLE PRECISION NOT NULL,
    "DATAINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PEDIDOS_pkey" PRIMARY KEY ("CODPED")
);

-- CreateTable
CREATE TABLE "ItensPedido" (
    "CODITEM" SERIAL NOT NULL,
    "CODPROD" INTEGER,
    "CODPED" INTEGER,

    CONSTRAINT "ItensPedido_pkey" PRIMARY KEY ("CODITEM")
);

-- AddForeignKey
ALTER TABLE "PRODUTO" ADD CONSTRAINT "PRODUTO_CODCAT_fkey" FOREIGN KEY ("CODCAT") REFERENCES "Categorias"("CODCAT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ItensPedido" ADD CONSTRAINT "ItensPedido_CODPROD_fkey" FOREIGN KEY ("CODPROD") REFERENCES "PRODUTO"("CODPROD") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ItensPedido" ADD CONSTRAINT "ItensPedido_CODPED_fkey" FOREIGN KEY ("CODPED") REFERENCES "PEDIDOS"("CODPED") ON DELETE SET NULL ON UPDATE CASCADE;
