name: Build and push reacts image

on: 
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Autenticando no Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Push da imagem no docker Hub
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./frontend
        file: ./frontend/Dockerfile.yml
        push: true
        tags: |
            pnunes276/zabbixstore-frontend:latest
            pnunes276/zabbixstore-frontend:v${{ github.run_number }}
        
        
  
  
